/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.yh342.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

/**
 * The main interface of the game, consists of read from input (file),
 * write to output (file), and show the prompts and gameplay.
 */
public class App {
    TextPlayer player1;
    TextPlayer player2;

    /**
     * Initialize App with two player objects
     *
     * @param player1 the first player
     * @param player2 the second player
     */
    public App(TextPlayer player1, TextPlayer player2) {
        this.player1 = player1;
        this.player2 = player2;
    }

    /**
     * Do replacement for each player in one turn
     */
    public void doPlacementPhase() throws IOException {
        player1.doPlacementPhase();
        player2.doPlacementPhase();
    }


    /**
     * Continually play the game until one player loses
     *
     * @param enemyBoard the enemy board
     * @param enemyView  the enemy board view
     * @param enemyName  the enemy name
     * @throws IOException if I/O operation fails
     */
    public void doAttackingPhase() throws IOException {
        boolean isGameEnds = false;
        boolean isPlayer1Turn = true;
        while (!isGameEnds) {
            if (isPlayer1Turn) {
                isGameEnds = player1.playOneTurn(player2.theBoard, player2.view, player2.name);
            } else {
                isGameEnds = player2.playOneTurn(player1.theBoard, player1.view, player1.name);
            }
            isPlayer1Turn = !isPlayer1Turn;
        }
    }

    /**
     * Main Entrance: build the game board, set input and output source,
     * and do one replacement
     *
     * @throws IOException if I/O operation fails
     */
    public static void main(String[] args) throws IOException {
        Board<Character> b1 = new BattleShipBoard<Character>(10, 20, 'X');
        Board<Character> b2 = new BattleShipBoard<Character>(10, 20, 'X');
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        V1ShipFactory factory = new V1ShipFactory();
        TextPlayer p1 = new TextPlayer("A", b1, input, System.out, factory);
        TextPlayer p2 = new TextPlayer("B", b2, input, System.out, factory);

        App app = new App(p1, p2);
        app.doPlacementPhase();
        app.doAttackingPhase();
    }
}
